import type BuildData from "./BuildData.ts";
import type { ExtInit } from "./ts-types.ts";
export declare class abConfs_Class {
    get abBootstrapDatetimepicker(): ExtInit;
    get abBootstrap(): ExtInit;
    get abCookies(): ExtInit;
    get abDataNative(): ExtInit;
    get abDataWeb(): ExtInit;
    get abData(): ExtInit;
    get abDatabaseNative(): ExtInit;
    get abDate(): ExtInit;
    get abFields(): ExtInit;
    get abGallery(): ExtInit;
    get abLayouts(): ExtInit;
    get abLock(): ExtInit;
    get abNative(): ExtInit;
    get abNodes(): ExtInit;
    get abPager(): ExtInit;
    get abQrCodesGenerator(): ExtInit;
    get abResourcePreloader(): ExtInit;
    get abStrings(): ExtInit;
    get abTextParser(): ExtInit;
    get abText(): ExtInit;
    get abTime(): ExtInit;
    get abTimer(): ExtInit;
    get abWebScroller(): ExtInit;
    get eSpkLemonBee(): ExtInit;
    get eLibs(): (build: BuildData, espadaFSPath: string) => BuildData;
    get eTasks(): ExtInit;
    get fontAwesome(): ExtInit;
    get jquery(): ExtInit;
    get js0(): ExtInit;
    get moment(): ExtInit;
    get sortablejs(): ExtInit;
    get spkFileUpload(): ExtInit;
    get spkForms(): ExtInit;
    get spkLemonBee(): ExtInit;
    get spkMessages(): ExtInit;
    get spkTables(): ExtInit;
    get spkTinymce(): ExtInit;
    get spocky(): ExtInit;
    get webABApi(): ExtInit;
    constructor();
}
declare const abConfs: abConfs_Class;
export default abConfs;
