export declare class abConfs_Class {
    get abBootstrapDatetimepicker(): (build: import("./BuildData.ts").default) => import("./BuildData.ts").default;
    get abBootstrap(): (build: import("./BuildData.ts").default) => import("./BuildData.ts").default;
    get abCookies(): (build: import("./BuildData.ts").default) => import("./BuildData.ts").default;
    get abDataNative(): (build: import("./BuildData.ts").default) => import("./BuildData.ts").default;
    get abDataWeb(): (build: import("./BuildData.ts").default) => import("./BuildData.ts").default;
    get abData(): (build: import("./BuildData.ts").default) => import("./BuildData.ts").default;
    get abDatabaseNative(): (build: import("./BuildData.ts").default) => import("./BuildData.ts").default;
    get abDate(): (build: import("./BuildData.ts").default) => import("./BuildData.ts").default;
    get abFields(): (build: import("./BuildData.ts").default) => import("./BuildData.ts").default;
    get abGallery(): (build: import("./BuildData.ts").default) => import("./BuildData.ts").default;
    get abLayouts(): (build: import("./BuildData.ts").default) => import("./BuildData.ts").default;
    get abLock(): (build: import("./BuildData.ts").default) => import("./BuildData.ts").default;
    get abNative(): (build: import("./BuildData.ts").default) => import("./BuildData.ts").default;
    get abNodes(): (build: import("./BuildData.ts").default) => import("./BuildData.ts").default;
    get abPager(): (build: import("./BuildData.ts").default) => import("./BuildData.ts").default;
    get abQrCodesGenerator(): (build: import("./BuildData.ts").default) => import("./BuildData.ts").default;
    get abResourcePreloader(): (build: import("./BuildData.ts").default) => import("./BuildData.ts").default;
    get abStrings(): (build: import("./BuildData.ts").default) => import("./BuildData.ts").default;
    get abTextParser(): (build: import("./BuildData.ts").default) => import("./BuildData.ts").default;
    get abText(): (build: import("./BuildData.ts").default) => import("./BuildData.ts").default;
    get abTime(): (build: import("./BuildData.ts").default) => import("./BuildData.ts").default;
    get abTimer(): (build: import("./BuildData.ts").default) => import("./BuildData.ts").default;
    get abWebScroller(): (build: import("./BuildData.ts").default) => import("./BuildData.ts").default;
    get eSpkLemonBee(): (build: import("./BuildData.ts").default) => import("./BuildData.ts").default;
    get eTasks(): (build: import("./BuildData.ts").default) => import("./BuildData.ts").default;
    get fontAwesome(): (build: import("./BuildData.ts").default) => import("./BuildData.ts").default;
    get jquery(): (build: import("./BuildData.ts").default) => import("./BuildData.ts").default;
    get js0(): (build: import("./BuildData.ts").default) => import("./BuildData.ts").default;
    get moment(): (build: import("./BuildData.ts").default) => import("./BuildData.ts").default;
    get sortablejs(): (build: import("./BuildData.ts").default) => import("./BuildData.ts").default;
    get spkFileUpload(): (build: import("./BuildData.ts").default) => import("./BuildData.ts").default;
    get spkForms(): (build: import("./BuildData.ts").default) => import("./BuildData.ts").default;
    get spkLemonBee(): (build: import("./BuildData.ts").default) => import("./BuildData.ts").default;
    get spkMessages(): (build: import("./BuildData.ts").default) => import("./BuildData.ts").default;
    get spkTables(): (build: import("./BuildData.ts").default) => import("./BuildData.ts").default;
    get spkTinymce(): (build: import("./BuildData.ts").default) => import("./BuildData.ts").default;
    get spocky(): (build: import("./BuildData.ts").default) => import("./BuildData.ts").default;
    get webABApi(): (build: import("./BuildData.ts").default) => import("./BuildData.ts").default;
    constructor();
}
declare const abConfs: abConfs_Class;
export default abConfs;
//# sourceMappingURL=ab-confs.d.ts.map